import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { projectsApi } from "../../api/projectsApi";
import SearchBar from "../../ui/SearchBar";
import { AdminButton, AdminCard, AdminLink, ConfirmDialog, PageHeader, StatusMessage } from "../components/AdminUI";
import { createQuery, formatDate, getList } from "../utils/forms";

function ProjectsList() {
  const [query, setQuery] = useState("");
  const [pendingDelete, setPendingDelete] = useState(null);
  const queryClient = useQueryClient();

  const { data = [], isPending, isError, error } = useQuery({
    queryKey: ["admin", "projects"],
    queryFn: () => projectsApi.list(createQuery({ sort: "-createdAt", limit: 100 })),
    select: getList,
  });

  const deleteMutation = useMutation({
    mutationFn: (id) => projectsApi.remove(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["admin", "projects"] });
      queryClient.invalidateQueries({ queryKey: ["projects"] });
      setPendingDelete(null);
    },
    onError: () => setPendingDelete(null),
  });

  const filtered = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    if (!normalized) return data;
    return data.filter((project) => {
      return (
        (project.title || "").toLowerCase().includes(normalized) ||
        (project.description || "").toLowerCase().includes(normalized) ||
        (project.technologies || []).some((tech) => tech.toLowerCase().includes(normalized))
      );
    });
  }, [data, query]);

  return (
    <section>
      <PageHeader
        eyebrow="Content"
        title="Projects"
        description="Create, edit, and remove portfolio projects. Slugs are generated by the backend from the title."
        action={<AdminLink to="/admin/projects/new">New project</AdminLink>}
      />

      <AdminCard className="space-y-5">
        <SearchBar value={query} onChange={setQuery} placeholder="Search projects..." />
        {deleteMutation.isError && (
          <StatusMessage type="error">
            {deleteMutation.error?.message || "Failed to delete project."}
          </StatusMessage>
        )}

        {isPending ? (
          <StatusMessage>Loading projects...</StatusMessage>
        ) : isError ? (
          <StatusMessage type="error">{error?.message || "Failed to load projects."}</StatusMessage>
        ) : filtered.length ? (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[760px] text-left text-sm">
              <thead className="text-xs uppercase tracking-wide text-gray-400">
                <tr className="border-b border-slate-700/50">
                  <th className="py-3 pr-4">Title</th>
                  <th className="py-3 pr-4">Technologies</th>
                  <th className="py-3 pr-4">Updated</th>
                  <th className="py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-700/40">
                {filtered.map((project) => {
                  const id = project._id ?? project.id;
                  return (
                    <tr key={id} className="align-top text-gray-300">
                      <td className="py-4 pr-4">
                        <p className="font-semibold text-gray-100">{project.title}</p>
                        <p className="mt-1 line-clamp-2 text-xs text-gray-500">{project.slogan || project.description}</p>
                      </td>
                      <td className="py-4 pr-4">
                        <div className="flex flex-wrap gap-2">
                          {(project.technologies || []).slice(0, 4).map((tech) => (
                            <span key={tech} className="rounded-full bg-primary-800/70 px-2.5 py-1 text-xs text-primary-100">
                              {tech}
                            </span>
                          ))}
                        </div>
                      </td>
                      <td className="py-4 pr-4 text-gray-400">{formatDate(project.updatedAt || project.createdAt)}</td>
                      <td className="py-4">
                        <div className="flex justify-end gap-2">
                          <Link className="rounded-xl border border-slate-700/60 px-3 py-2 text-xs font-semibold text-gray-200 transition hover:border-primary-400/50 hover:text-primary-100" to={`/admin/projects/${id}/edit`}>
                            Edit
                          </Link>
                          <AdminButton variant="danger" className="px-3 py-2 text-xs" onClick={() => setPendingDelete(project)}>
                            Delete
                          </AdminButton>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        ) : (
          <StatusMessage>No projects found.</StatusMessage>
        )}
      </AdminCard>

      {pendingDelete && (
        <ConfirmDialog
          title="Delete project?"
          message={`This will permanently delete "${pendingDelete.title}".`}
          onCancel={() => setPendingDelete(null)}
          onConfirm={() => deleteMutation.mutate(pendingDelete._id ?? pendingDelete.id)}
          busy={deleteMutation.isPending}
        />
      )}
    </section>
  );
}

export default ProjectsList;
